---
name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64,arm,amd64

    - name: Dockerhub Readme
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: qjoly
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        readme: ./README.md
        repository: "qjoly/jekyll"
      if: github.event_name != 'pull_request'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Dockerhub registry
      uses: docker/login-action@v2
      with:
        username: qjoly
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      if: github.event_name != 'pull_request'

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
         context: .
         platforms: linux/amd64,linux/arm64
         push: true
         tags: qjoly/jekyll
      if: github.event_name != 'pull_request'
      
    - name: ntfy_action
      uses: NiNiyas/ntfy-action@v1.0.1
      with:
        title: "CI Jekyll terminé"
        url: https://ntfy.thoughtless.eu
        topic: github_cicd

